#!/bin/bash
echo ""
echo ""
echo "     Starting Data Analysis Toolbox"
echo ""
echo ""
echo ""
echo "     Welcome to "
echo ""
echo ""
echo "                 █████╗ ███╗   ███╗██████╗ ██╗     ██╗███████╗██╗     ██╗"
echo "                ██╔══██╗████╗ ████║██╔══██╗██║     ██║██╔════╝╚██╗   ██╔╝"
echo "                ███████║██╔████╔██║██████╔╝██║     ██║█████╗     ╚████╔╝ "
echo "                ██╔══██║██║╚██╔╝██║██╔═══╝ ██║     ██║██╔══╝      ╚██╔╝  "
echo "                ██║  ██║██║ ╚═╝ ██║██║     ███████╗██║██║          ██║   "
echo "                ╚═╝  ╚═╝╚═╝     ╚═╝╚═╝     ╚══════╝╚═╝╚═╝          ╚═╝   "
echo "                                                           "
echo "                                                           "
echo "                                      A M P L I F Y                         "
echo "                                                           "
echo "     (Automated MRI Preprocessing for Localized Injection-based Functional activitY)"                  
echo "                                                           "
echo "              Authored by Dr. Naman Jain                       "
echo "              Max Planck Institute for Biological Cybernetics  "
echo "              Tübingen, Germany                                "
echo "                                                           "
